apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: mattermost-success
          image: mattermost:final
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***"
          - name: url
            value: "172.17.0.232"
          - name: token
            value: "irimgj777jd4jxhkkdwnau41pr"
          - name: scheme
            value: "http"
          - name: port
            value: "32659"
          - name: channel_name
            value: "argocd-course"
          - name: team_name
            value: "DevOps-Hobbies"
      restartPolicy: Never
  backoffLimit: 0
